# Generated by Django 5.1 on 2025-01-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=200, null=True),
        ),
    ]
