# Generated by Django 5.1 on 2025-01-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_alter_serviceoffer_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
