# Generated by Django 5.1 on 2025-01-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0004_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='donate_to_org',
        ),
    ]
