# Generated by Django 5.1 on 2025-01-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0005_remove_organization_donate_to_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='Price',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
