# Generated by Django 5.1 on 2025-01-23 18:23

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0006_remove_servicerequest_status_servicerequest_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
