# Generated by Django 5.1 on 2025-01-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0007_remove_servicerequest_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatetoorg',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.organization'),
        ),
        migrations.AlterField(
            model_name='donatetoorg',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
