# Generated by Django 5.1 on 2025-01-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0008_donatetoorg_organization_alter_donatetoorg_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='admin',
        ),
    ]
