# Generated by Django 5.1 on 2025-01-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0010_remove_cart_cart_id_remove_cart_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Manage.cart'),
        ),
    ]
